// Copyright 2024 Ahyve AI Inc.
// SPDX-License-Identifier: BUSL-1.1

/**
 * Builtin Tools Support
 *
 * This module provides types and utilities for OpenAI's builtin tools
 * available in the Responses API:
 * - apply_patch: Create, update, or delete files using unified diffs
 * - web_search: Search the web for information
 * - file_search: Search through uploaded files
 * - code_interpreter: Execute Python code
 * - computer_use: Control a virtual computer
 */

import log from "loglevel";

// ============================================================================
// Builtin Tool Types Enum
// ============================================================================

/**
 * Enum of all supported builtin tool types
 */
export enum BuiltinToolType {
  ApplyPatch = "apply_patch",
  WebSearch = "web_search",
  WebSearchPreview = "web_search_preview",
  FileSearch = "file_search",
  CodeInterpreter = "code_interpreter",
  ComputerUse = "computer_use_preview",
}

// ============================================================================
// Apply Patch Types
// ============================================================================

/**
 * Operation to create a new file
 */
export interface ApplyPatchCreateFile {
  type: "create_file";
  /** Path of the file to create relative to workspace root */
  path: string;
  /** Unified diff content to apply when creating the file */
  diff: string;
}

/**
 * Operation to delete an existing file
 */
export interface ApplyPatchDeleteFile {
  type: "delete_file";
  /** Path of the file to delete relative to workspace root */
  path: string;
}

/**
 * Operation to update an existing file
 */
export interface ApplyPatchUpdateFile {
  type: "update_file";
  /** Path of the file to update relative to workspace root */
  path: string;
  /** Unified diff content to apply */
  diff: string;
}

/**
 * Union of all apply_patch operations
 */
export type ApplyPatchOperation =
  | ApplyPatchCreateFile
  | ApplyPatchDeleteFile
  | ApplyPatchUpdateFile;

/**
 * An apply_patch tool call from the model
 */
export interface ApplyPatchCall {
  /** The unique ID of the apply patch tool call (from API) */
  id: string;
  /** The unique ID of the apply patch tool call generated by the model */
  call_id: string;
  /** Type discriminator */
  type: "apply_patch_call";
  /** The file operation to perform */
  operation: ApplyPatchOperation;
  /** Status of the tool call */
  status: "in_progress" | "completed";
}

/**
 * Result of an apply_patch operation to send back to the model
 */
export interface ApplyPatchResult {
  /** The call_id from the original ApplyPatchCall */
  call_id: string;
  /** Whether the operation succeeded or failed */
  status: "completed" | "failed";
  /** Optional output message (e.g., error details) */
  output?: string;
}

// ============================================================================
// Web Search Types
// ============================================================================

/**
 * A web_search tool call from the model
 */
export interface WebSearchCall {
  /** The unique ID of the web search tool call */
  id: string;
  /** Type discriminator */
  type: "web_search_call";
  /** Status of the search */
  status: "in_progress" | "searching" | "completed" | "failed";
}

// ============================================================================
// File Search Types
// ============================================================================

/**
 * A file_search tool call from the model
 */
export interface FileSearchCall {
  /** The unique ID of the file search tool call */
  id: string;
  /** Type discriminator */
  type: "file_search_call";
  /** Status of the search */
  status: "in_progress" | "searching" | "completed";
  /** Search queries performed */
  queries?: string[];
  /** Search results (when completed) */
  results?: FileSearchResult[];
}

export interface FileSearchResult {
  /** File ID */
  file_id: string;
  /** File name */
  file_name: string;
  /** Relevance score */
  score: number;
  /** Matched text snippets */
  text?: string;
}

// ============================================================================
// Code Interpreter Types
// ============================================================================

/**
 * A code_interpreter tool call from the model
 */
export interface CodeInterpreterCall {
  /** The unique ID of the code interpreter tool call */
  id: string;
  /** Type discriminator */
  type: "code_interpreter_call";
  /** The Python code to execute */
  code: string;
  /** Status of the execution */
  status: "in_progress" | "interpreting" | "completed";
  /** Outputs from code execution (when completed) */
  outputs?: CodeInterpreterOutput[];
}

export interface CodeInterpreterOutput {
  type: "logs" | "image" | "file";
  /** Log output text */
  logs?: string;
  /** Base64 encoded image */
  image?: string;
  /** File reference */
  file_id?: string;
}

// ============================================================================
// Computer Use Types
// ============================================================================

/**
 * A computer_use tool call from the model
 */
export interface ComputerUseCall {
  /** The unique ID of the computer use tool call */
  id: string;
  /** The call ID */
  call_id: string;
  /** Type discriminator */
  type: "computer_call";
  /** Action to perform */
  action: ComputerAction;
  /** Status of the action */
  status: "in_progress" | "completed";
}

export type ComputerAction =
  | { type: "click"; x: number; y: number; button?: "left" | "right" | "middle" }
  | { type: "double_click"; x: number; y: number }
  | { type: "scroll"; x: number; y: number; scroll_x: number; scroll_y: number }
  | { type: "type"; text: string }
  | { type: "key"; key: string }
  | { type: "wait"; ms: number }
  | { type: "screenshot" }
  | { type: "move"; x: number; y: number }
  | { type: "drag"; start_x: number; start_y: number; end_x: number; end_y: number };

export interface ComputerUseResult {
  call_id: string;
  /** Screenshot after action (base64) */
  output?: {
    type: "computer_screenshot";
    image_url: string;
  };
}

// ============================================================================
// Union Types
// ============================================================================

/**
 * Union of all builtin tool calls
 */
export type BuiltinToolCall =
  | ApplyPatchCall
  | WebSearchCall
  | FileSearchCall
  | CodeInterpreterCall
  | ComputerUseCall;

/**
 * Union of all builtin tool results that need to be sent back
 */
export type BuiltinToolResult = ApplyPatchResult | ComputerUseResult;

/**
 * Check if a type string is a builtin tool call type
 */
export function isBuiltinToolCallType(type: string): boolean {
  return [
    "apply_patch_call",
    "web_search_call",
    "file_search_call",
    "code_interpreter_call",
    "computer_call",
  ].includes(type);
}

/**
 * Check if a builtin tool call type requires a response to be sent back
 */
export function requiresResponse(type: string): boolean {
  return ["apply_patch_call", "computer_call"].includes(type);
}

// ============================================================================
// Builtin Tool Specifications
// ============================================================================

/**
 * Tool specification for apply_patch
 */
export interface ApplyPatchToolSpec {
  type: "apply_patch";
}

/**
 * Tool specification for web_search
 */
export interface WebSearchToolSpec {
  type: "web_search_preview" | "web_search_preview_2025_03_11" | "web_search" | "web_search_2025_08_26";
  /** Optional search context size */
  search_context_size?: "low" | "medium" | "high";
  /** User location for search personalization */
  user_location?: {
    type: "approximate";
    city?: string;
    country?: string;
    region?: string;
    timezone?: string;
  };
}

/**
 * Tool specification for file_search
 */
export interface FileSearchToolSpec {
  type: "file_search";
  /** Vector store IDs to search */
  vector_store_ids: string[];
  /** Maximum number of results */
  max_num_results?: number;
  /** Ranking options */
  ranking_options?: {
    ranker?: "auto" | "default_2024_08_21";
    score_threshold?: number;
  };
}

/**
 * Tool specification for code_interpreter
 */
export interface CodeInterpreterToolSpec {
  type: "code_interpreter";
  /** Container for code execution */
  container?: {
    type: "auto" | "none";
  };
}

/**
 * Tool specification for computer_use
 */
export interface ComputerUseToolSpec {
  type: "computer_use_preview";
  /** Display dimensions */
  display_width: number;
  display_height: number;
  /** Environment type */
  environment: "windows" | "mac" | "linux" | "ubuntu" | "browser";
}

/**
 * Union of all builtin tool specifications
 */
export type BuiltinToolSpec =
  | ApplyPatchToolSpec
  | WebSearchToolSpec
  | FileSearchToolSpec
  | CodeInterpreterToolSpec
  | ComputerUseToolSpec;

/**
 * Create a tool spec for a builtin tool type
 */
export function createBuiltinToolSpec(
  type: BuiltinToolType,
  options?: Partial<BuiltinToolSpec>
): BuiltinToolSpec {
  switch (type) {
    case BuiltinToolType.ApplyPatch:
      return { type: "apply_patch" };
    case BuiltinToolType.WebSearch:
      return { type: "web_search", ...options } as WebSearchToolSpec;
    case BuiltinToolType.WebSearchPreview:
      return { type: "web_search_preview", ...options } as WebSearchToolSpec;
    case BuiltinToolType.FileSearch:
      if (!options || !("vector_store_ids" in options)) {
        throw new Error("file_search requires vector_store_ids");
      }
      return { type: "file_search", ...options } as FileSearchToolSpec;
    case BuiltinToolType.CodeInterpreter:
      return { type: "code_interpreter", ...options } as CodeInterpreterToolSpec;
    case BuiltinToolType.ComputerUse:
      if (!options || !("display_width" in options) || !("display_height" in options) || !("environment" in options)) {
        throw new Error("computer_use requires display_width, display_height, and environment");
      }
      return { type: "computer_use_preview", ...options } as ComputerUseToolSpec;
    default:
      throw new Error(`Unknown builtin tool type: ${type}`);
  }
}

// ============================================================================
// Handler Types
// ============================================================================

/**
 * Handler function type for builtin tool calls
 */
export type BuiltinToolHandler<T extends BuiltinToolCall, R extends BuiltinToolResult | void> = (
  call: T
) => Promise<R>;

/**
 * Registry entry for a builtin tool handler
 */
export interface BuiltinToolHandlerEntry {
  type: string;
  handler: BuiltinToolHandler<any, any>;
}

// ============================================================================
// Output Filtering
// ============================================================================

/**
 * Options for filtering output items before sending back to the model
 */
export interface OutputFilterOptions {
  /**
   * Exclude these output item types from being sent back.
   * E.g., ["web_search_call", "file_search_call"] to hide search details.
   */
  excludeTypes?: string[];

  /**
   * Custom filter function. Return false to exclude an item.
   * Called after excludeTypes filtering.
   */
  filter?: (item: any) => boolean;
}

/**
 * Filter output items based on options
 */
export function filterOutputItems<T extends { type: string }>(
  items: T[],
  options?: OutputFilterOptions
): T[] {
  if (!options) return items;

  let filtered = items;

  if (options.excludeTypes && options.excludeTypes.length > 0) {
    filtered = filtered.filter((item) => !options.excludeTypes!.includes(item.type));
  }

  if (options.filter) {
    filtered = filtered.filter(options.filter);
  }

  return filtered;
}

// ============================================================================
// Error Handling
// ============================================================================

/**
 * Create an error result for an unhandled builtin tool call
 */
export function createUnhandledError(call: BuiltinToolCall): BuiltinToolResult | null {
  log.warn(`Unhandled builtin tool call: ${call.type} (id: ${call.id})`);

  if (call.type === "apply_patch_call") {
    return {
      call_id: (call as ApplyPatchCall).call_id,
      status: "failed",
      output: `Error: No handler registered for builtin tool '${call.type}'. Please register a handler using registerBuiltinToolHandler() or the @handleBuiltinTool decorator.`,
    } as ApplyPatchResult;
  }

  if (call.type === "computer_call") {
    return {
      call_id: (call as ComputerUseCall).call_id,
      output: undefined,
    } as ComputerUseResult;
  }

  // Other builtin tools (web_search, file_search, code_interpreter) don't require responses
  return null;
}

